---
abstract: 'Write RDF/Turtle documents without non-core package dependencies'
author:
  - 'Jakob Voss'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Turtle-Writer
requires:
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/nichtich/Turtle-Writer/issues
  homepage: https://github.com/nichtich/Turtle-Writer
  repository: https://github.com/nichtich/Turtle-Writer.git
version: 0.003
